@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3ODAyMjQ5NywiZXhwIjoxNzc4MDUxMjk3fQ.8Y1ZEiS7PikVye4No6WAhtzoWPWNgPkl8pMmF_-VmOY

GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/active

###
GET http://localhost:3000/api/users/11

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
  "firstName": "Pedro",
  "lastName": "Teste",
  "phone": "2499999-4444",
  "role": "user",
  "email": "p@p.com",
  "password": "gus1234!"
}

###

DELETE http://localhost:3000/api/users/11
Authorization: Bearer {{authToken}}

###

PATCH  http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "email": "Hansen de Oliveira 22"
}

###
PATCH  http://localhost:3000/api/users/4/toggle

###
PATCH  http://localhost:3000/api/users/role/11
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "role": "admin"
}