### Create a new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "firstName": "Johnny",
  "lastName": "Silverhand",
  "isActive": true
}

### Get all users
GET http://localhost:3000/api/users

### Get a user by ID
GET http://localhost:3000/api/users/2

### Update a user
PUT http://localhost:3000/api/users/2
Content-Type: application/json

{
  "firstName": "Vincent",
  "lastName": "Vega",
  "isActive": false
}

### Delete a user
DELETE http://localhost:3000/api/users/2

### Update a user
PATCH http://localhost:3000/api/users/1
Content-Type: application/json

{
  "isActive": false
}